### Numpy Problems

In [19]:
import numpy as np

#### 1.Creating Arrays

In [20]:
random_arr = np.random.randint(10,51,20)
print(random_arr)

[34 34 23 29 49 17 30 23 16 17 28 13 40 20 21 16 22 43 39 45]


In [21]:
mean_arr = np.mean(random_arr)
print(mean_arr)

27.95


In [22]:
stdev_arr = np.std(random_arr)
print(stdev_arr)

10.608840652964865


#### 2. Array Reshaping

In [23]:
random_farr = np.random.rand(6,5)
print(random_farr)

[[0.66130191 0.42567702 0.17869297 0.69845241 0.89045904]
 [0.99524881 0.22548988 0.51355101 0.30776361 0.82486415]
 [0.54387357 0.27254014 0.69023049 0.19063615 0.91375389]
 [0.93526822 0.8258276  0.20058679 0.06138994 0.11193172]
 [0.66800036 0.2346195  0.26473379 0.8864206  0.22400944]
 [0.97423901 0.28935504 0.9341204  0.13383562 0.50208161]]


In [24]:
reshaped_arr = random_farr.reshape(5,6)
print(reshaped_arr)

[[0.66130191 0.42567702 0.17869297 0.69845241 0.89045904 0.99524881]
 [0.22548988 0.51355101 0.30776361 0.82486415 0.54387357 0.27254014]
 [0.69023049 0.19063615 0.91375389 0.93526822 0.8258276  0.20058679]
 [0.06138994 0.11193172 0.66800036 0.2346195  0.26473379 0.8864206 ]
 [0.22400944 0.97423901 0.28935504 0.9341204  0.13383562 0.50208161]]


### 3. Array indexing and Slicing

In [25]:
arr1 = np.arange(1,26).reshape(5,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
# find the subarray that includes row 2 to 4 and columnn 1 to 3
arr2 = arr1[1:4,0:3]
print(arr2)

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


#### 4. Array Operations

In [29]:
A = np.random.randint(1,101,10)
B = np.random.randint(1,101,10)
print("A = ", A)
print("B =" ,B)


A =  [87 43 53 27  5 60  1 45 23 61]
B = [82  5  5 31 17 34 83 80 23 81]


In [30]:
sum_arr = A+B
print(sum_arr)

[169  48  58  58  22  94  84 125  46 142]


In [32]:
output_arr = sum_arr*2
print(output_arr)

[338  96 116 116  44 188 168 250  92 284]


#### 5. Broadcasting

In [39]:
A = np.random.randint(1,11,(3,4))
print(A)

[[ 9  4  7 10]
 [ 3  9  3  6]
 [10  6  1  1]]


In [42]:
B = np.array([1,2,3,4])
print(B)


[1 2 3 4]


In [43]:
f_arr = A+B
print(f_arr)

[[10  6 10 14]
 [ 4 11  6 10]
 [11  8  4  5]]


#### 6. Finding Maximum / Minimum values

In [44]:
rand_matrix = np.random.randint(1,101,(3,3))
print(rand_matrix)

[[ 80  88  55]
 [ 91  16  53]
 [ 90 100  15]]


In [47]:
sum_raw = np.sum(rand_matrix,axis = 1)
print(sum_raw)

[223 160 205]


In [50]:
index_sum_raw = np.argmax(sum_raw)
print(index_sum_raw)
# to find the index of the row with the maximum sum

0


In [51]:
max_value = np.max(rand_matrix[index_sum_raw])
print(max_value)

88


#### 7. Linear Algebra

In [71]:
A = np.random.randint(1,30,(2,2))
B = np.random.randint(1,30,(2,2))
print(" A =  \n",A,'\n' )

print(" B = \n", B,'\n')


 A =  
 [[21  8]
 [19  2]] 

 B = 
 [[ 7 28]
 [20 13]] 



matrix_mul = np.dot(A,B)
print(matrix_mul)

#### 8. Boolean indexing

In [73]:
arr = np.random.randint(1,51,(6,6))
print(arr)

[[37 26 37  5  6 28]
 [27 13 48 32 34 46]
 [23 27 21 45  4 13]
 [43 40 41 22  1 26]
 [31  4 32 21  5  2]
 [13 46 14 11 17 48]]


In [74]:
max_arr = arr[arr>25]
print(max_arr)

[37 26 37 28 27 48 32 34 46 27 45 43 40 41 26 31 32 46 48]


#### 9. Statistics

In [76]:
random_float = np.random.rand(5,5)
print(random_float)

[[0.66552737 0.9843824  0.99820252 0.96699921 0.42887003]
 [0.65892417 0.91197884 0.69992069 0.07691961 0.21101145]
 [0.36810508 0.57439001 0.93431218 0.36470056 0.33908377]
 [0.192103   0.37086349 0.20801128 0.46309256 0.24289521]
 [0.99577693 0.10534316 0.4792036  0.82775983 0.38150101]]


In [78]:
raw_median = np.median(random_float, axis = 1)
print(raw_median)

[0.96699921 0.65892417 0.36810508 0.24289521 0.4792036 ]


In [79]:
column_median = np.median(random_float, axis =0)
print(column_median)

[0.65892417 0.57439001 0.69992069 0.46309256 0.33908377]


In [80]:
raw_variance = np.var(random_float,axis = 1)
print(raw_variance)

[0.05132066 0.09935454 0.05089164 0.01097587 0.10133559]


In [81]:
column_variance = np.var(random_float,axis = 0)
print(column_variance)

[0.07634028 0.10847254 0.08562514 0.10324442 0.00676413]


#### 10. Element- wise operations

In [82]:
arr = np.random.randint(1,11,(3,3))
print(arr)

[[10 10  6]
 [ 1  8  1]
 [ 2  4  6]]


In [84]:
sub_arr = arr -2
print(sub_arr)

[[ 8  8  4]
 [-1  6 -1]
 [ 0  2  4]]


In [85]:
sq_arr = arr ** 2
print(sq_arr)

[[100 100  36]
 [  1  64   1]
 [  4  16  36]]


In [86]:
reci_arr = 1/arr
print(reci_arr)

[[0.1        0.1        0.16666667]
 [1.         0.125      1.        ]
 [0.5        0.25       0.16666667]]


In [88]:
# using  np.reciprocal
r_arr = np.reciprocal(arr.astype(float))
print(r_arr)


[[0.1        0.1        0.16666667]
 [1.         0.125      1.        ]
 [0.5        0.25       0.16666667]]


### Pandas

#### 1.Basic Exploration

In [106]:
# Loading the dataset 
df = pd.read_csv("auto-mpg.csv")

In [109]:
# first 10 rows
df.head(10)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [110]:
# total number of rows and columns 
df.shape

(398, 9)

In [112]:
#summary statistics for numerical columns
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

#### 2. Filtering and indexing

In [115]:
car_filtered = df[(df["model year"]== 75) & (df["weight"]<3000)]
result = car_filtered[["car name", "weight", "mpg"]]
print(result)

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0


#### 3. Handling missing data

In [117]:
df.isnull()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    False      False         False       False   False         False   
1    False      False         False       False   False         False   
2    False      False         False       False   False         False   
3    False      False         False       False   False         False   
4    False      False         False       False   False         False   
..     ...        ...           ...         ...     ...           ...   
393  False      False         False       False   False         False   
394  False      False         False       False   False         False   
395  False      False         False       False   False         False   
396  False      False         False       False   False         False   
397  False      False         False       False   False         False   

     model year  origin  car name  
0         False   False     False  
1         False   False     False  
2         False   False     False  
3         False   False     False  
4         False   False     False  
..          ...     ...       ...  
393       False   False     False  
394       False   False     False  
395       False   False     False  
396       False   False     False  
397       False   False     False  

[398 rows x 9 columns]

In [119]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [121]:
df.horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [125]:
median_hp = df[(df['horsepower']!='?')]['horsepower'].astype(int).median()
median_hp1 = df['horsepower'].values
median_hp1[median_hp1=='?'] = median_hp

In [126]:
df['horsepower'] = median_hp1.astype(int)

In [127]:
df['horsepower']

0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: int64

In [128]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64  
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(5), object(1)
memory usage: 28.1+ KB


In [130]:
df.horsepower.unique()

array([130, 165, 150, 140, 198, 220, 215, 225, 190, 170, 160,  95,  97,
        85,  88,  46,  87,  90, 113, 200, 210, 193,  93, 100, 105, 175,
       153, 180, 110,  72,  86,  70,  76,  65,  69,  60,  80,  54, 208,
       155, 112,  92, 145, 137, 158, 167,  94, 107, 230,  49,  75,  91,
       122,  67,  83,  78,  52,  61, 148, 129,  96,  71,  98, 115,  53,
        81,  79, 120, 152, 102, 108,  68,  58, 149,  89,  63,  48,  66,
       139, 103, 125, 133, 138, 135, 142,  77,  62, 132,  84,  64,  74,
       116,  82])

#### 4. Data Transformation

In [132]:
df['power_to_weight_ratio'] = df['horsepower']/df['weight']
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

#### 5. Group by

In [137]:
df.groupby('origin')['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

#### 6. Sorting

In [151]:
# sorting by mpg in ascending order
df_sorted = df.sort_values(by='mpg', ascending = False)
top_10_cars =df_sorted.head(10)
print("Top 10 cars with highest mpg \n" , top_10_cars[['car name','mpg']])

Top 10 cars with highest mpg 
                             car name   mpg
322                        mazda glc  46.6
329              honda civic 1500 gl  44.6
325             vw rabbit c (diesel)  44.3
394                        vw pickup  44.0
326               vw dasher (diesel)  43.4
244  volkswagen rabbit custom diesel  43.1
309                        vw rabbit  41.5
330             renault lecar deluxe  40.9
324                       datsun 210  40.8
247                   datsun b210 gx  39.4


#### 7. Apply Function

In [160]:
def performance_score(row):
    return row['mpg'] * row ['acceleration']/ row['weight']

df['performance_score'] = df.apply(performance_score, axis =1)

print(df[['car name', 'mpg', 'acceleration', 'weight', 'performance_score']])

                      car name   mpg  acceleration  weight  performance_score
0    chevrolet chevelle malibu  18.0          12.0    3504           0.061644
1            buick skylark 320  15.0          11.5    3693           0.046710
2           plymouth satellite  18.0          11.0    3436           0.057625
3                amc rebel sst  16.0          12.0    3433           0.055928
4                  ford torino  17.0          10.5    3449           0.051754
..                         ...   ...           ...     ...                ...
393            ford mustang gl  27.0          15.6    2790           0.150968
394                  vw pickup  44.0          24.6    2130           0.508169
395              dodge rampage  32.0          11.6    2295           0.161743
396                ford ranger  28.0          18.6    2625           0.198400
397                 chevy s-10  31.0          19.4    2720           0.221103

[398 rows x 5 columns]


#### 8. Visualization Preparation

In [165]:
df_summary = df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()
print("Summary Dataframe",df_summary)

Summary Dataframe                   mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.535714
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.185185
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.551724
81          30.334483  2522.931034   81.448276
82          31.709677  2453.548387   81.838710


#### 9. Exporting Data

In [168]:
high_mpg_cars = df[df['mpg']>30][['mpg','cylinders','horsepower','weight']]
high_mpg_cars.to_csv( 'high_mpg_cars.csv',index = False)
print("New revised data stored as  'high_mpg_cars.csv'.")

New revised data stored as  'high_mpg_cars.csv'.


#### 10. Finding Anomalies

In [171]:
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)

IQR = Q3- Q1

lower_bound = Q1-1.5 *IQR
upper_bound = Q3 +1.5*IQR

outliers =  df[(df['mpg']<lower_bound) | (df['mpg']>upper_bound)]
df_outliers = outliers[['car name','mpg', 'model year']]

print ("Dataframe of cars classified as outliers")
df_outliers

Dataframe of cars classified as outliers


car name   mpg  model year
322  mazda glc  46.6          80